"""
doc_generator.py — Document generation engine for RunawayScout reports.
Produces high-quality Word (.docx), Excel (.xlsx), PowerPoint (.pptx),
and PDF/HTML reports with professional layout designs.
"""
import os
import re
import time
from datetime import datetime

# Safe package imports
try:
    import docx
    from docx.shared import Inches, Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.oxml import OxmlElement, parse_xml
    from docx.oxml.ns import nsdecls, qn
except ImportError:
    docx = None

try:
    import openpyxl
    from openpyxl.styles import Font, Alignment, PatternFill, Border, Side
    from openpyxl.utils import get_column_letter
except ImportError:
    openpyxl = None

try:
    import pptx
    from pptx.util import Inches as PtInches, Pt as PtSize
    from pptx.dml.color import RGBColor as PptRGBColor
    from pptx.enum.text import PP_ALIGN
except ImportError:
    pptx = None


# ── Word Helpers ──────────────────────────────────────────────────────

def set_cell_background(cell, fill_hex):
    """Set background color of a Word table cell."""
    tcPr = cell._tc.get_or_add_tcPr()
    shd = parse_xml(f'<w:shd {nsdecls("w")} w:fill="{fill_hex}"/>')
    tcPr.append(shd)

def set_cell_margins(cell, top=100, bottom=100, left=150, right=150):
    """Set margins (padding) of a Word table cell."""
    tcPr = cell._tc.get_or_add_tcPr()
    tcMar = OxmlElement('w:tcMar')
    for m, val in [('w:top', top), ('w:bottom', bottom), ('w:left', left), ('w:right', right)]:
        node = OxmlElement(m)
        node.set(qn('w:w'), str(val))
        node.set(qn('w:type'), 'dxa')
        tcMar.append(node)
    tcPr.append(tcMar)


# ── Document Generators ───────────────────────────────────────────────

def generate_word(research_data: dict, metadata: dict) -> str:
    """Generate professional Word Document (.docx) report."""
    if docx is None:
        raise ImportError("python-docx is not installed.")

    doc = docx.Document()
    
    # 1-inch margins
    for section in doc.sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1)
        section.right_margin = Inches(1)

    # Cover Page
    title_p = doc.add_paragraph()
    title_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_p.paragraph_format.space_before = Pt(80)
    title_run = title_p.add_run(metadata.get("title", "AI Research Report"))
    title_run.font.name = 'Calibri'
    title_run.font.size = Pt(28)
    title_run.font.bold = True
    title_run.font.color.rgb = RGBColor(30, 27, 75)  # Indigo-950 #1E1B4B

    meta_p = doc.add_paragraph()
    meta_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    meta_p.paragraph_format.space_before = Pt(40)
    meta_run = meta_p.add_run(
        f"Generated by RunawayScout AI Research Assistant\n"
        f"Date: {datetime.now().strftime('%B %d, %Y')}\n"
        f"Original Query: \"{metadata.get('query', '')}\""
    )
    meta_run.font.name = 'Calibri'
    meta_run.font.size = Pt(11)
    meta_run.font.italic = True
    meta_run.font.color.rgb = RGBColor(100, 116, 139)  # Slate-500

    doc.add_page_break()

    # Executive Summary Section
    h_exec = doc.add_heading(level=1)
    h_exec_run = h_exec.add_run("Executive Summary")
    h_exec_run.font.name = 'Calibri'
    h_exec_run.font.color.rgb = RGBColor(79, 70, 229)  # Indigo-600 #4F46E5

    summary_text = research_data.get("summary", "No executive summary available.")
    for p_text in summary_text.split("\n\n"):
        if p_text.strip():
            p = doc.add_paragraph(p_text.strip())
            p.paragraph_format.line_spacing = 1.15
            p.paragraph_format.space_after = Pt(10)

    # Key Takeaways
    takeaways = research_data.get("key_takeaways", [])
    if takeaways:
        h_take = doc.add_heading("Key Strategic Takeaways", level=2)
        h_take.runs[0].font.color.rgb = RGBColor(30, 27, 75)
        for take in takeaways:
            p = doc.add_paragraph(style='List Bullet')
            p.add_run(take)

    doc.add_page_break()

    # Sections / Vectors
    sections = research_data.get("sections", [])
    for sec in sections:
        sec_title = sec.get("title", "Research findings")
        h_sec = doc.add_heading(level=1)
        h_sec_run = h_sec.add_run(sec_title)
        h_sec_run.font.name = 'Calibri'
        h_sec_run.font.color.rgb = RGBColor(79, 70, 229)  # Indigo-600

        content = sec.get("content", "")
        for p_text in content.split("\n\n"):
            if p_text.strip():
                p = doc.add_paragraph(p_text.strip())
                p.paragraph_format.line_spacing = 1.15
                p.paragraph_format.space_after = Pt(10)

        # Key findings under vector
        kf = sec.get("key_findings", [])
        if kf:
            h_insights = doc.add_heading("Core Insights", level=2)
            h_insights.runs[0].font.color.rgb = RGBColor(30, 27, 75)
            for item in kf:
                p = doc.add_paragraph(style='List Bullet')
                p.add_run(item)

        # Vector Table Data
        tbl_data = sec.get("data", [])
        if tbl_data and isinstance(tbl_data, list):
            doc.add_heading("Extracted Parameter Matrix", level=2)
            cols = []
            for row in tbl_data:
                if isinstance(row, dict):
                    for k in row.keys():
                        if k not in cols:
                            cols.append(k)
            
            if cols:
                table = doc.add_table(rows=1, cols=len(cols))
                table.style = 'Light Shading Accent 1'
                
                # Format headers
                hdr_cells = table.rows[0].cells
                for c_idx, col in enumerate(cols):
                    hdr_cells[c_idx].text = str(col).replace("_", " ").title()
                    set_cell_background(hdr_cells[c_idx], "4F46E5")  # Indigo-600
                    set_cell_margins(hdr_cells[c_idx])
                    for p in hdr_cells[c_idx].paragraphs:
                        for r in p.runs:
                            r.font.bold = True
                            r.font.color.rgb = RGBColor(255, 255, 255)

                # Format data rows
                for r_idx, row in enumerate(tbl_data):
                    row_cells = table.add_row().cells
                    bg_color = "F8FAFC" if r_idx % 2 == 1 else "FFFFFF"
                    for c_idx, col in enumerate(cols):
                        val = row.get(col, "")
                        row_cells[c_idx].text = str(val if val is not None else "-")
                        set_cell_background(row_cells[c_idx], bg_color)
                        set_cell_margins(row_cells[c_idx])

        doc.add_paragraph().paragraph_format.space_after = Pt(12)

    # Sources List
    doc.add_page_break()
    h_src = doc.add_heading(level=1)
    h_src_run = h_src.add_run("Sources & References")
    h_src_run.font.name = 'Calibri'
    h_src_run.font.color.rgb = RGBColor(79, 70, 229)

    sources = research_data.get("sources", [])
    if sources:
        for idx, src in enumerate(sources):
            p = doc.add_paragraph()
            p.add_run(f"[{idx+1}] ").bold = True
            
            title = src.get("title") or src.get("url") or "Link"
            url = src.get("url") or ""
            tier = src.get("tier_label") or src.get("label", "Tier 6")
            score = src.get("quality_score") or src.get("score", 50)
            
            p.add_run(title).bold = True
            if url and url != title:
                p.add_run(f" — {url}")
            p.add_run(f" ({tier} | Quality Score: {score}/100)").italic = True
    else:
        doc.add_paragraph("No sources recorded.")

    # Save to outputs
    output_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "outputs")
    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    file_path = os.path.join(output_dir, f"scout_report_{timestamp}.docx")
    doc.save(file_path)
    return file_path


def generate_excel(research_data: dict, metadata: dict) -> str:
    """Generate structured Excel Workbook (.xlsx) report with allowlist sheets."""
    if openpyxl is None:
        raise ImportError("openpyxl is not installed.")

    # Pre-filter using presentation_filter to get allowlist blocks if not already done
    from presentation_filter import build_presentable
    if "sections" not in research_data and "tables" not in research_data:
        research_data = build_presentable(research_data)

    wb = openpyxl.Workbook()
    wb.remove(wb.active)  # Remove default sheet

    # Colors & Fonts
    navy_fill = PatternFill(start_color="1E1B4B", end_color="1E1B4B", fill_type="solid")
    indigo_fill = PatternFill(start_color="4F46E5", end_color="4F46E5", fill_type="solid")
    zebra_fill = PatternFill(start_color="F8FAFC", end_color="F8FAFC", fill_type="solid")
    
    white_font = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
    bold_font = Font(name="Calibri", size=11, bold=True)
    normal_font = Font(name="Calibri", size=11)
    
    thin_border = Border(
        left=Side(style='thin', color='E2E8F0'),
        right=Side(style='thin', color='E2E8F0'),
        top=Side(style='thin', color='E2E8F0'),
        bottom=Side(style='thin', color='E2E8F0')
    )

    # Compile master tools list and category statistics
    all_tools = []
    category_counts = {}
    
    for table in research_data.get("tables", []):
        cat_title = table.get("title", "General")
        rows = table.get("rows", [])
        category_counts[cat_title] = len(rows)
        for row in rows:
            row_copy = dict(row)
            row_copy["category"] = cat_title
            all_tools.append(row_copy)

    # 1. Tools Sheet
    ws_tools = wb.create_sheet(title="Tools")
    ws_tools.views.sheetView[0].showGridLines = True
    
    headers_tools = ["Category", "Name", "URL", "Purpose / Description", "Key Features", "Typical Use Cases", "Free Limitations"]
    for c_idx, h in enumerate(headers_tools):
        cell = ws_tools.cell(row=1, column=c_idx+1, value=h)
        cell.font = white_font
        cell.fill = navy_fill
        cell.alignment = Alignment(horizontal="center")
        cell.border = thin_border

    for r_idx, tool in enumerate(all_tools):
        row_num = 2 + r_idx
        fill = zebra_fill if r_idx % 2 == 1 else PatternFill(fill_type=None)
        
        ws_tools.cell(row=row_num, column=1, value=tool.get("category") or "").font = normal_font
        ws_tools.cell(row=row_num, column=2, value=tool.get("name") or "").font = bold_font
        ws_tools.cell(row=row_num, column=3, value=tool.get("url") or "").font = normal_font
        ws_tools.cell(row=row_num, column=4, value=tool.get("purpose") or "").font = normal_font
        ws_tools.cell(row=row_num, column=5, value=tool.get("key_features") or "").font = normal_font
        ws_tools.cell(row=row_num, column=6, value=tool.get("use_cases") or "").font = normal_font
        ws_tools.cell(row=row_num, column=7, value=tool.get("free_limitations") or "").font = normal_font

        for col in range(1, 8):
            cell = ws_tools.cell(row=row_num, column=col)
            cell.border = thin_border
            if fill.fill_type:
                cell.fill = fill

    for col in ws_tools.columns:
        max_len = max(len(str(cell.value or '')) for cell in col)
        col_letter = get_column_letter(col[0].column)
        ws_tools.column_dimensions[col_letter].width = min(max(max_len + 3, 12), 50)

    # 2. Categories Sheet
    ws_cats = wb.create_sheet(title="Categories")
    ws_cats.views.sheetView[0].showGridLines = True
    ws_cats.cell(row=1, column=1, value="Category").font = white_font
    ws_cats.cell(row=1, column=1).fill = navy_fill
    ws_cats.cell(row=1, column=1).border = thin_border
    ws_cats.cell(row=1, column=2, value="Tool Count").font = white_font
    ws_cats.cell(row=1, column=2).fill = navy_fill
    ws_cats.cell(row=1, column=2).border = thin_border

    for r_idx, (cat, count) in enumerate(category_counts.items()):
        row_num = 2 + r_idx
        fill = zebra_fill if r_idx % 2 == 1 else PatternFill(fill_type=None)
        
        ws_cats.cell(row=row_num, column=1, value=cat).font = bold_font
        ws_cats.cell(row=row_num, column=2, value=count).font = normal_font

        for col in range(1, 3):
            cell = ws_cats.cell(row=row_num, column=col)
            cell.border = thin_border
            if fill.fill_type:
                cell.fill = fill
                
    ws_cats.column_dimensions["A"].width = 30
    ws_cats.column_dimensions["B"].width = 15

    # 3. Free Tier Limits Sheet
    ws_limits = wb.create_sheet(title="Free_Tier_Limits")
    ws_limits.views.sheetView[0].showGridLines = True
    ws_limits.cell(row=1, column=1, value="Tool Name").font = white_font
    ws_limits.cell(row=1, column=1).fill = navy_fill
    ws_limits.cell(row=1, column=1).border = thin_border
    ws_limits.cell(row=1, column=2, value="URL").font = white_font
    ws_limits.cell(row=1, column=2).fill = navy_fill
    ws_limits.cell(row=1, column=2).border = thin_border
    ws_limits.cell(row=1, column=3, value="Free Tier Limitations & Constraints").font = white_font
    ws_limits.cell(row=1, column=3).fill = navy_fill
    ws_limits.cell(row=1, column=3).border = thin_border

    limit_idx = 0
    for tool in all_tools:
        lims = tool.get("free_limitations")
        if lims and str(lims).strip() and str(lims).lower() not in ("none", "n/a", "null"):
            row_num = 2 + limit_idx
            fill = zebra_fill if limit_idx % 2 == 1 else PatternFill(fill_type=None)
            
            ws_limits.cell(row=row_num, column=1, value=tool.get("name") or "").font = bold_font
            ws_limits.cell(row=row_num, column=2, value=tool.get("url") or "").font = normal_font
            ws_limits.cell(row=row_num, column=3, value=lims).font = normal_font

            for col in range(1, 4):
                cell = ws_limits.cell(row=row_num, column=col)
                cell.border = thin_border
                if fill.fill_type:
                    cell.fill = fill
            limit_idx += 1

    for col in ws_limits.columns:
        max_len = max(len(str(cell.value or '')) for cell in col)
        col_letter = get_column_letter(col[0].column)
        ws_limits.column_dimensions[col_letter].width = min(max(max_len + 3, 12), 60)

    # 4. Sources Sheet
    ws_src = wb.create_sheet(title="Sources")
    ws_src.views.sheetView[0].showGridLines = True
    headers_src = ["#", "Source Title", "Domain", "Reference URL", "Tier"]
    for c_idx, h in enumerate(headers_src):
        cell = ws_src.cell(row=1, column=c_idx+1, value=h)
        cell.font = white_font
        cell.fill = navy_fill
        cell.alignment = Alignment(horizontal="center")
        cell.border = thin_border

    sources = research_data.get("sources", [])
    for r_idx, src in enumerate(sources):
        row_num = 2 + r_idx
        fill = zebra_fill if r_idx % 2 == 1 else PatternFill(fill_type=None)
        
        ws_src.cell(row=row_num, column=1, value=r_idx+1).font = bold_font
        ws_src.cell(row=row_num, column=2, value=src.get("title") or "").font = normal_font
        ws_src.cell(row=row_num, column=3, value=src.get("domain") or "").font = normal_font
        ws_src.cell(row=row_num, column=4, value=src.get("url") or "").font = normal_font
        ws_src.cell(row=row_num, column=5, value=src.get("tier") or "").font = normal_font

        for col in range(1, 6):
            cell = ws_src.cell(row=row_num, column=col)
            cell.border = thin_border
            if fill.fill_type:
                cell.fill = fill

    for col in ws_src.columns:
        max_len = max(len(str(cell.value or '')) for cell in col)
        col_letter = get_column_letter(col[0].column)
        ws_src.column_dimensions[col_letter].width = min(max(max_len + 3, 10), 60)

    # 5. Coverage Gaps Sheet
    ws_gaps = wb.create_sheet(title="Coverage_Gaps")
    ws_gaps.views.sheetView[0].showGridLines = True
    ws_gaps.cell(row=1, column=1, value="Vector / Topic").font = white_font
    ws_gaps.cell(row=1, column=1).fill = navy_fill
    ws_gaps.cell(row=1, column=1).border = thin_border
    ws_gaps.cell(row=1, column=2, value="Reason").font = white_font
    ws_gaps.cell(row=1, column=2).fill = navy_fill
    ws_gaps.cell(row=1, column=2).border = thin_border

    gaps = research_data.get("gaps", [])
    for r_idx, gap in enumerate(gaps):
        row_num = 2 + r_idx
        fill = zebra_fill if r_idx % 2 == 1 else PatternFill(fill_type=None)
        
        ws_gaps.cell(row=row_num, column=1, value=gap.get("topic") or gap.get("vector_id") or "").font = bold_font
        ws_gaps.cell(row=row_num, column=2, value=gap.get("reason") or "Insufficient usable data captured.").font = normal_font

        for col in range(1, 3):
            cell = ws_gaps.cell(row=row_num, column=col)
            cell.border = thin_border
            if fill.fill_type:
                cell.fill = fill

    ws_gaps.column_dimensions["A"].width = 30
    ws_gaps.column_dimensions["B"].width = 50

    output_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "outputs")
    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    file_path = os.path.join(output_dir, f"scout_report_{timestamp}.xlsx")
    wb.save(file_path)
    return file_path


def generate_pptx(research_data: dict, metadata: dict) -> str:
    """Generate high-quality PowerPoint slide presentation (.pptx)."""
    if pptx is None:
        raise ImportError("python-pptx is not installed.")

    prs = pptx.Presentation()
    blank_layout = prs.slide_layouts[6]

    def add_indigo_header(slide, title_text):
        """Top banner header for content slides."""
        banner = slide.shapes.add_shape(
            pptx.enum.shapes.MSO_SHAPE.RECTANGLE,
            PtInches(0), PtInches(0), PtInches(10), PtInches(1)
        )
        banner.fill.solid()
        banner.fill.fore_color.rgb = PptRGBColor(30, 27, 75)  # Navy #1E1B4B
        banner.line.fill.background()
        
        txBox = slide.shapes.add_textbox(PtInches(0.5), PtInches(0.1), PtInches(9), PtInches(0.8))
        tf = txBox.text_frame
        tf.word_wrap = True
        p = tf.paragraphs[0]
        p.text = title_text
        p.font.name = 'Calibri'
        p.font.size = PtSize(24)
        p.font.bold = True
        p.font.color.rgb = PptRGBColor(255, 255, 255)

    # Slide 1: Cover Slide
    cover_slide = prs.slides.add_slide(blank_layout)
    bg = cover_slide.shapes.add_shape(
        pptx.enum.shapes.MSO_SHAPE.RECTANGLE,
        PtInches(0), PtInches(0), PtInches(10), PtInches(7.5)
    )
    bg.fill.solid()
    bg.fill.fore_color.rgb = PptRGBColor(30, 27, 75)
    bg.line.fill.background()

    title_box = cover_slide.shapes.add_textbox(PtInches(1), PtInches(2.5), PtInches(8), PtInches(2))
    tf = title_box.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = metadata.get("title", "Research report")
    p.font.name = 'Calibri'
    p.font.size = PtSize(38)
    p.font.bold = True
    p.font.color.rgb = PptRGBColor(255, 255, 255)
    p.alignment = PP_ALIGN.CENTER

    p2 = tf.add_paragraph()
    p2.text = f"Prepared by RunawayScout AI Research Assistant\nDate: {datetime.now().strftime('%B %d, %Y')}"
    p2.font.name = 'Calibri'
    p2.font.size = PtSize(16)
    p2.font.color.rgb = PptRGBColor(226, 232, 240)
    p2.alignment = PP_ALIGN.CENTER

    # Slide 2: Executive Summary
    summary_slide = prs.slides.add_slide(blank_layout)
    add_indigo_header(summary_slide, "Executive Summary")
    
    tx_box = summary_slide.shapes.add_textbox(PtInches(0.5), PtInches(1.5), PtInches(9), PtInches(5))
    tf = tx_box.text_frame
    tf.word_wrap = True

    takeaways = research_data.get("key_takeaways", [])
    if takeaways:
        p = tf.paragraphs[0]
        p.text = "Strategic takeaways & outcomes:"
        p.font.name = 'Calibri'
        p.font.bold = True
        p.font.size = PtSize(18)
        
        for take in takeaways[:5]:
            p_t = tf.add_paragraph()
            p_t.text = f"• {take}"
            p_t.font.name = 'Calibri'
            p_t.font.size = PtSize(14)
            p_t.space_before = PtSize(6)
    else:
        summary = research_data.get("summary", "")
        p = tf.paragraphs[0]
        p.text = summary[:600] + "..." if len(summary) > 600 else summary
        p.font.name = 'Calibri'
        p.font.size = PtSize(15)

    # Slide 3+: Section Slides
    sections = research_data.get("sections", [])
    for sec in sections[:6]:  # Limit deck size
        sec_title = sec.get("title", "Findings")
        slide = prs.slides.add_slide(blank_layout)
        add_indigo_header(slide, sec_title)

        # Left Column - text insights
        tx_left = slide.shapes.add_textbox(PtInches(0.5), PtInches(1.5), PtInches(4.5), PtInches(5))
        tf_left = tx_left.text_frame
        tf_left.word_wrap = True
        
        p = tf_left.paragraphs[0]
        p.text = "Key Findings:"
        p.font.bold = True
        p.font.size = PtSize(16)
        
        kf = sec.get("key_findings", [])
        if kf:
            for item in kf[:4]:
                p_i = tf_left.add_paragraph()
                p_i.text = f"• {item}"
                p_i.font.size = PtSize(13)
                p_i.space_before = PtSize(5)
        else:
            p_c = tf_left.add_paragraph()
            content = sec.get("content", "")
            p_c.text = content[:350] + "..." if len(content) > 350 else content
            p_c.font.size = PtSize(13)

        # Right Column - Data Matrix (if applicable)
        tbl_data = sec.get("data", [])
        if tbl_data and isinstance(tbl_data, list):
            cols = []
            for row in tbl_data:
                if isinstance(row, dict):
                    for k in row.keys():
                        if k not in cols:
                            cols.append(k)
            cols = cols[:3]
            rows_data = tbl_data[:4]

            if cols and rows_data:
                rows_cnt = len(rows_data) + 1
                cols_cnt = len(cols)
                
                table_shape = slide.shapes.add_table(
                    rows_cnt, cols_cnt,
                    PtInches(5.2), PtInches(1.7), PtInches(4.3), PtInches(4.5)
                )
                table = table_shape.table
                
                # Form headers
                for c_idx, col in enumerate(cols):
                    cell = table.cell(0, c_idx)
                    cell.text = str(col).replace("_", " ").title()
                    cell.fill.solid()
                    cell.fill.fore_color.rgb = PptRGBColor(79, 70, 229)
                    for p in cell.text_frame.paragraphs:
                        p.font.name = 'Calibri'
                        p.font.size = PtSize(11)
                        p.font.bold = True
                        p.font.color.rgb = PptRGBColor(255, 255, 255)
                        
                # Form data
                for r_idx, row in enumerate(rows_data):
                    for c_idx, col in enumerate(cols):
                        cell = table.cell(r_idx+1, c_idx)
                        cell.text = str(row.get(col, "") or "-")
                        cell.fill.solid()
                        bg_color = PptRGBColor(248, 250, 252) if r_idx % 2 == 1 else PptRGBColor(255, 255, 255)
                        cell.fill.fore_color.rgb = bg_color
                        for p in cell.text_frame.paragraphs:
                            p.font.size = PtSize(10)

    # Slide Last: Sources
    src_slide = prs.slides.add_slide(blank_layout)
    add_indigo_header(src_slide, "Sources & Reference Citations")
    
    tx_src = src_slide.shapes.add_textbox(PtInches(0.5), PtInches(1.5), PtInches(9), PtInches(5))
    tf_src = tx_src.text_frame
    tf_src.word_wrap = True

    sources = research_data.get("sources", [])
    if sources:
        p = tf_src.paragraphs[0]
        p.text = "The following authoritative sources were compiled:"
        p.font.bold = True
        p.font.size = PtSize(16)
        
        for idx, src in enumerate(sources[:6]):
            p_s = tf_src.add_paragraph()
            title = src.get("title") or src.get("url") or "Link"
            tier = src.get("tier_label") or src.get("label", "Tier 6")
            p_s.text = f"[{idx+1}] {title} ({tier})"
            p_s.font.size = PtSize(13)
            p_s.space_before = PtSize(5)
    else:
        tf_src.paragraphs[0].text = "No sources recorded."

    output_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "outputs")
    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    file_path = os.path.join(output_dir, f"scout_report_{timestamp}.pptx")
    prs.save(file_path)
    return file_path


def generate_pdf(research_data: dict, metadata: dict) -> str:
    """Generate high-quality HTML report (converts to PDF if weasyprint available)."""
    title = metadata.get("title", "Research Report")
    query = metadata.get("query", "")
    summary = research_data.get("summary", "")
    sections = research_data.get("sections", [])
    sources = research_data.get("sources", [])
    takeaways = research_data.get("key_takeaways", [])

    sections_html = ""
    for sec in sections:
        sec_title = sec.get("title", "Research Section")
        sec_content = "".join([f"<p>{p.strip()}</p>" for p in sec.get("content", "").split("\n\n") if p.strip()])
        
        findings_li = "".join([f"<li>{kf}</li>" for kf in sec.get("key_findings", [])])
        findings_html = f"<div class='insights'><h3>Key Insights</h3><ul>{findings_li}</ul></div>" if findings_li else ""
        
        table_html = ""
        tbl_data = sec.get("data", [])
        if tbl_data and isinstance(tbl_data, list):
            cols = []
            for row in tbl_data:
                if isinstance(row, dict):
                    for k in row.keys():
                        if k not in cols:
                            cols.append(k)
            if cols:
                hdr_th = "".join([f"<th>{str(c).replace('_', ' ').title()}</th>" for c in cols])
                rows_tr = ""
                for idx, row in enumerate(tbl_data):
                    tr_class = "class='zebra'" if idx % 2 == 1 else ""
                    cells_td = "".join([f"<td>{str(row.get(col, '') or '-')}</td>" for col in cols])
                    rows_tr += f"<tr {tr_class}>{cells_td}</tr>"
                table_html = f"<div class='table-container'><table><thead><tr>{hdr_th}</tr></thead><tbody>{rows_tr}</tbody></table></div>"

        sections_html += f"""
        <section class="report-section">
            <h2>{sec_title}</h2>
            <div class="content">{sec_content}</div>
            {findings_html}
            {table_html}
        </section>
        <hr class="section-divider"/>
        """

    takeaways_html = ""
    if takeaways:
        takeaways_li = "".join([f"<li>{t}</li>" for t in takeaways])
        takeaways_html = f"""
        <div class="takeaways-box">
            <h3>Key Strategic Takeaways</h3>
            <ul>{takeaways_li}</ul>
        </div>
        """

    sources_html = ""
    if sources:
        sources_li = ""
        for idx, src in enumerate(sources):
            s_title = src.get("title") or src.get("url") or "Link"
            s_url = src.get("url") or ""
            tier = src.get("tier_label") or src.get("label", "Tier 6")
            score = src.get("quality_score") or src.get("score", 50)
            
            badge_class = "badge-t1" if "tier 1" in tier.lower() else "badge-t2" if "tier 2" in tier.lower() else "badge-t3" if "tier 3" in tier.lower() else "badge-t4" if "tier 4" in tier.lower() else "badge-t5" if "tier 5" in tier.lower() else "badge-t6"
            
            sources_li += f"""
            <li>
                <div class="source-item">
                    <span class="source-num">[{idx+1}]</span>
                    <a href="{s_url}" target="_blank" class="source-title">{s_title}</a>
                    <span class="badge {badge_class}">{tier}</span>
                    <span class="source-score">Quality Score: {score}/100</span>
                </div>
            </li>
            """
        sources_html = f"<ol class='sources-list'>{sources_li}</ol>"
    else:
        sources_html = "<p>No sources recorded.</p>"

    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{title}</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');
        
        body {{
            font-family: 'Inter', sans-serif;
            color: #1E293B;
            line-height: 1.6;
            margin: 0;
            padding: 40px auto;
            max-width: 900px;
            background-color: #F8FAFC;
        }}
        
        .report-card {{
            background: #FFFFFF;
            padding: 50px;
            border-radius: 12px;
            box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1);
            margin: 40px auto;
            border: 1px solid #E2E8F0;
        }}
        
        header {{
            border-bottom: 2px solid #E2E8F0;
            padding-bottom: 30px;
            margin-bottom: 40px;
            text-align: center;
        }}
        
        h1 {{
            color: #1E1B4B;
            font-size: 32px;
            margin-top: 0;
            margin-bottom: 10px;
            font-weight: 700;
        }}
        
        .meta-info {{
            color: #64748B;
            font-size: 14px;
            margin-bottom: 5px;
            font-style: italic;
        }}
        
        h2 {{
            color: #4F46E5;
            font-size: 22px;
            border-left: 4px solid #4F46E5;
            padding-left: 12px;
            margin-top: 30px;
            margin-bottom: 15px;
        }}
        
        h3 {{
            color: #1E293B;
            font-size: 16px;
            margin-top: 0;
            margin-bottom: 10px;
        }}
        
        p {{
            margin-top: 0;
            margin-bottom: 15px;
            font-size: 15px;
            text-align: justify;
        }}
        
        .takeaways-box {{
            background: #EEF2F6;
            border-radius: 8px;
            padding: 20px;
            margin: 25px 0;
            border: 1px solid #CBD5E1;
        }}
        
        .takeaways-box ul, .insights ul {{
            margin: 0;
            padding-left: 20px;
        }}
        
        .takeaways-box li, .insights li {{
            margin-bottom: 8px;
            font-size: 14px;
        }}
        
        .insights {{
            background: #F0FDFA;
            border-left: 4px solid #0D9488;
            border-radius: 4px;
            padding: 15px;
            margin: 20px 0;
        }}
        
        .insights h3 {{
            color: #0F766E;
        }}
        
        .table-container {{
            width: 100%;
            overflow-x: auto;
            margin: 25px 0;
            border: 1px solid #E2E8F0;
            border-radius: 6px;
        }}
        
        table {{
            width: 100%;
            border-collapse: collapse;
            font-size: 14px;
            text-align: left;
        }}
        
        th {{
            background: #4F46E5;
            color: #FFFFFF;
            font-weight: 600;
            padding: 12px 16px;
        }}
        
        td {{
            padding: 12px 16px;
            border-bottom: 1px solid #E2E8F0;
        }}
        
        tr.zebra {{
            background: #F8FAFC;
        }}
        
        .section-divider {{
            border: 0;
            height: 1px;
            background: #E2E8F0;
            margin: 40px 0;
        }}
        
        .sources-list {{
            padding-left: 0;
            list-style: none;
        }}
        
        .source-item {{
            display: flex;
            align-items: center;
            flex-wrap: wrap;
            margin-bottom: 12px;
            font-size: 14px;
        }}
        
        .source-num {{
            font-weight: 600;
            margin-right: 8px;
            color: #64748B;
        }}
        
        .source-title {{
            color: #2563EB;
            text-decoration: none;
            font-weight: 500;
            margin-right: 10px;
        }}
        
        .source-title:hover {{
            text-decoration: underline;
        }}
        
        .badge {{
            font-size: 11px;
            font-weight: 600;
            padding: 2px 8px;
            border-radius: 9999px;
            margin-right: 10px;
        }}
        
        .badge-t1 {{ background: #FEE2E2; color: #991B1B; }}
        .badge-t2 {{ background: #FEF3C7; color: #92400E; }}
        .badge-t3 {{ background: #ECFDF5; color: #065F46; }}
        .badge-t4 {{ background: #E0F2FE; color: #075985; }}
        .badge-t5 {{ background: #F5F3FF; color: #5B21B6; }}
        .badge-t6 {{ background: #F1F5F9; color: #475569; }}
        
        .source-score {{
            color: #64748B;
            font-size: 12px;
        }}
        
        @media print {{
            body {{
                background: #FFFFFF;
                padding: 0;
            }}
            .report-card {{
                box-shadow: none;
                border: none;
                padding: 0;
                margin: 0;
            }}
            .report-section {{
                page-break-inside: avoid;
            }}
        }}
    </style>
</head>
<body>
    <div class="report-card">
        <header>
            <h1>{title}</h1>
            <div class="meta-info">Generated by RunawayScout AI Research Assistant</div>
            <div class="meta-info">Original Query: "{query}"</div>
            <div class="meta-info">Date: {datetime.now().strftime("%B %d, %Y")}</div>
        </header>
        
        <section class="report-section">
            <h2>Executive Summary</h2>
            <p>{summary.replace('\n', '<br/>')}</p>
            {takeaways_html}
        </section>
        
        <hr class="section-divider"/>
        
        {sections_html}
        
        <section class="report-section">
            <h2>Sources & References</h2>
            {sources_html}
        </section>
    </div>
</body>
</html>
"""
    output_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "outputs")
    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    file_path = os.path.join(output_dir, f"scout_report_{timestamp}.html")
    
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(html_content)
        
    try:
        import weasyprint
        pdf_path = os.path.join(output_dir, f"scout_report_{timestamp}.pdf")
        weasyprint.HTML(file_path).write_pdf(pdf_path)
        return pdf_path
    except Exception:
        print("    WeasyPrint not available, returning HTML format.")
        return file_path


def pre_filter_and_map_back(research_data: dict) -> dict:
    """Pre-filter research_data using presentation_filter, then map it back so that generate_word/pdf continue to function."""
    from presentation_filter import build_presentable
    
    # Check if already filtered (e.g., if it has gaps / executive_summary)
    if "executive_summary" in research_data and "gaps" in research_data:
        presentable = research_data
    else:
        presentable = build_presentable(research_data)
        
    # Map back to old schema format:
    mapped = {}
    mapped["summary"] = presentable.get("executive_summary") or ""
    mapped["key_takeaways"] = presentable.get("key_takeaways") or []
    
    # Rebuild sections
    sections = []
    for sec in presentable.get("sections", []):
        vid = sec.get("vector_id")
        
        # Find corresponding table rows for this section
        tbl_rows = []
        for t in presentable.get("tables", []):
            if t.get("vector_id") == vid:
                tbl_rows = t.get("rows", [])
                break
                
        sections.append({
            "title": sec.get("title", ""),
            "content": sec.get("body", ""),
            "key_findings": [],
            "data": tbl_rows
        })
    mapped["sections"] = sections
    
    # Map sources
    sources = []
    for src in presentable.get("sources", []):
        sources.append({
            "title": src.get("title"),
            "url": src.get("url"),
            "tier_label": src.get("tier"),
            "label": src.get("tier"),
            "quality_score": 90,  # placeholder/default
            "score": 90,
            "domain": src.get("domain"),
            "tier": src.get("tier"),
            "status": src.get("status")
        })
    mapped["sources"] = sources
    
    # Preserve gaps and tables for generate_excel
    mapped["gaps"] = presentable.get("gaps", [])
    mapped["tables"] = presentable.get("tables", [])
    
    return mapped


def generate_output(research_data: dict, metadata: dict, format_type: str) -> str:
    """Main route to generate documents."""
    raise RuntimeError(
        "doc_generator.generate_output is deprecated for research sessions. "
        "Use present.py against the run folder instead."
    )
